---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: satellite-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: satellite-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satellite-app
    spec:
      containers:
      - image: vindhyadk/satellite-mysql:main
        imagePullPolicy: Always
        name: satellite-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: satellite-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: satellite-app
  type: LoadBalancer
status:
  loadBalancer: {}