---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: satellite-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: satellite-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satellite-deploy
    spec:
      containers:
      - image: vindhyadk/satellite-mysql:main
        imagePullPolicy: Always
        name: satellite-deploy
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: satellite-service
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      nodePort: 30010
  selector:
    app.kubernetes.io/name: satellite-deploy